function BM = BMatrix(xi)

phi = xi(4);
th  = xi(5);
psi = xi(6);

BM=[cos(psi)*cos(th),-cos(phi)*sin(psi)+cos(psi)*sin(phi)*sin(th), ...
    sin(phi)*sin(psi)+cos(phi)*cos(psi)*sin(th),0,0,0;...
    cos(th)*sin(psi), cos(phi)*cos(psi)+sin(phi)*sin(psi)*sin(th),...
    -cos(psi)*sin(phi)+cos(phi)*sin(psi)*sin(th),0,0,0;...
    -sin(th),cos(th)*sin(phi),cos(phi)*cos(th),0,0,0;...
    0,0,0,1,sin(phi)*tan(th),cos(phi)*tan(th);...
    0,0,0,0,cos(phi),-sin(phi);0,0,0,0,sec(th)*sin(phi),cos(phi)*sec(th)];

end
