
function Jf = EndEfJacobian(xi, ArmConstants)

l1 = ArmConstants.l1_dim(1);
l2 = ArmConstants.l2_dim(2);
L  = ArmConstants.Hexa_to_joint_L;

phi = xi(4);
th  = xi(5);
psi = xi(6);
q1  = xi(7);
q2  = xi(8);

Jf=[1,0,0,sin(phi).*(sin(psi).*(l1.*sin(q1)+l2.*sin(q1+q2))+cos(psi).*(L+ ...
  l1.*cos(q1)+l2.*cos(q1+q2)).*sin(th))+cos(phi).*(sin(psi).*((-1).*L+l2.* ...
  sin(q1).*sin(q2))+cos(psi).*(l1+l2.*cos(q2)).*sin(q1).*sin(th)+cos(q1).* ...
  ((-1).*(l1+l2.*cos(q2)).*sin(psi)+l2.*cos(psi).*sin(q2).*sin(th))),(-1) ...
  .*cos(psi).*(L.*cos(phi)+l1.*cos(phi+q1)+l2.*cos(phi+q1+q2)).*cos(th),( ...
  -1).*(L+l1.*cos(q1)+l2.*cos(q1+q2)).*(cos(psi).*sin(phi)+(-1).*cos(phi) ...
  .*sin(psi).*sin(th))+(-1).*(l1.*sin(q1)+l2.*sin(q1+q2)).*(cos(phi).*cos( ...
  psi)+sin(phi).*sin(psi).*sin(th)),(l1.*sin(q1)+l2.*sin(q1+q2)).*(sin( ...
  phi).*sin(psi)+cos(phi).*cos(psi).*sin(th))+(l1.*cos(q1)+l2.*cos(q1+q2)) ...
  .*((-1).*cos(phi).*sin(psi)+cos(psi).*sin(phi).*sin(th)),l2.*sin(q1+q2) ...
  .*(sin(phi).*sin(psi)+cos(phi).*cos(psi).*sin(th))+l2.*cos(q1+q2).*((-1) ...
  .*cos(phi).*sin(psi)+cos(psi).*sin(phi).*sin(th));0,1,0,cos(psi).*(L.* ...
  cos(phi)+l1.*cos(phi+q1)+l2.*cos(phi+q1+q2)).*cos(th).^2+sin(th).*((L+ ...
  l1.*cos(q1)+l2.*cos(q1+q2)).*(sin(phi).*sin(psi)+cos(phi).*cos(psi).* ...
  sin(th))+(-1).*(l1.*sin(q1)+l2.*sin(q1+q2)).*((-1).*cos(phi).*sin(psi)+ ...
  cos(psi).*sin(phi).*sin(th))),(-1).*(L.*cos(phi)+l1.*cos(phi+q1)+l2.* ...
  cos(phi+q1+q2)).*cos(th).*sin(psi),(-1).*(L+l1.*cos(q1)+l2.*cos(q1+q2)) ...
  .*(sin(phi).*sin(psi)+cos(phi).*cos(psi).*sin(th))+(l1.*sin(q1)+l2.*sin( ...
  q1+q2)).*((-1).*cos(phi).*sin(psi)+cos(psi).*sin(phi).*sin(th)),(l1.* ...
  sin(q1)+l2.*sin(q1+q2)).*((-1).*cos(psi).*sin(phi)+cos(phi).*sin(psi).* ...
  sin(th))+(l1.*cos(q1)+l2.*cos(q1+q2)).*(cos(phi).*cos(psi)+sin(phi).* ...
  sin(psi).*sin(th)),l2.*sin(q1+q2).*((-1).*cos(psi).*sin(phi)+cos(phi).* ...
  sin(psi).*sin(th))+l2.*cos(q1+q2).*(cos(phi).*cos(psi)+sin(phi).*sin( ...
  psi).*sin(th));0,0,1,cos(th).*(L.*sin(phi)+l1.*sin(phi+q1)+l2.*sin(phi+ ...
  q1+q2)),(L.*cos(phi)+l1.*cos(phi+q1)+l2.*cos(phi+q1+q2)).*sin(th),0,cos( ...
  th).*(l1.*sin(phi+q1)+l2.*sin(phi+q1+q2)),l2.*cos(th).*sin(phi+q1+q2);0, ...
  0,0,cos(psi).*cos(th),(-1).*sin(psi),0,cos(psi).*cos(th),cos(psi).*cos( ...
  th);0,0,0,cos(th).*sin(psi),cos(psi),0,cos(th).*sin(psi),cos(th).*sin( ...
  psi);0,0,0,(-1).*sin(th),0,1,(-1).*sin(th),(-1).*sin(th)];


end
